### ISSUE TITLE
capture barista logs for user review through GUI

### ISSUE THREAD

**Issue by woodrbe** [Optum/barista#59]
Provide better feedback to users of the system when errors occur during scans.

Known errors: 
- Scanning needs access to repo

**Comment by pkn4645** [comment]
building on this concept, barista logs should capture and stash the results of every scan so they can be reviewed from the scan details page in the GUI - specifically perhaps a 3rd tab after license results and security results?

since this may create problematic storage issues, we should also have an easy mechanism for purging log results - perhaps each project should only store two scans, the current one and one back if it exists

@rolinge thoughts?

**Comment by rolinge** [comment]
I think if we give an option to push the log to an object store that is
super cheap, the cost won't be too bad.  But yes, there should be some
thinking about retention of information.
